
services:
  calorie-counter:
    container_name: calorie-counter
    ports:
      - "${LOCAL_DK_SERVER_PORT}:${LOCAL_DK_SERVER_PORT}"
    networks:
      - calorie-network
    image: calorie-image
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .\.env
    depends_on:
      calorie-counter-db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7.4-alpine
    container_name: ${LOCAL_DK_REDIS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${LOCAL_DK_REDIS_PORT}:6379"
    networks:
      - calorie-network
    command: >
      redis-server
      --appendonly yes
      --requirepass ${LOCAL_DK_REDIS_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "${LOCAL_DK_REDIS_PASSWORD}",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  calorie-counter-db:
    container_name: ${LOCAL_DK_HOST_NAME}
    ports:
      - "${LOCAL_DK_DB_SERVER_PORT}:27017"
    networks:
      - calorie-network
    image:  mongodb/mongodb-community-server:7.0-ubi8
    volumes:
      - calorie-volume:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  calorie-network:
    name: calorie-counter-network
    driver: bridge

volumes:
  calorie-volume:
    name: calorie-counter-volume