
services:
  calorie-counter:
    container_name: calorie-counter
    ports:
      - "${LOCAL_DK_SERVER_PORT}:${LOCAL_DK_SERVER_PORT}"
    networks:
      - calorie-network
    image: calorie-image
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .\.env
    depends_on:
      - calorie-counter-db

  calorie-counter-db:
    container_name: ${LOCAL_DK_HOST_NAME}
    ports:
      - "${LOCAL_DK_DB_SERVER_PORT}:27017"
    networks:
      - calorie-network
    image:  mongodb/mongodb-community-server:7.0-ubi8
    volumes:
      - calorie-volume:/data/db

networks:
  calorie-network:
    name: calorie-counter-network
    driver: bridge

volumes:
  calorie-volume:
    name: calorie-counter-volume